[SP-12422] stabilize order of actions taken on upload
Losant/losant-cli pull request #77
Opened 2023-10-26 17:54 UTC by eeerin

SP-12422

steps to reproduce are on the ticket in the comments.

2023-10-26 18:38 UTC, spacetc62 requested changes

2023-10-26 18:38 UTC, spacetc62 commented on lib/get-uploader.js
>          (stat === 'added' && remoteStatus === 'added') ||
should be `stat.status`?

2023-10-27 15:46 UTC, eeerin commented
the tests were failing on node 19, for some reason it couldnt download that version for a little while.

2023-10-30 13:33 UTC, spacetc62 approved these changes

2023-10-30 13:33 UTC, merged